### ISSUE TITLE
Alert _ids don't match the UUID field in document generator

### ISSUE THREAD

**Issue by jaredburgettelastic** [elastic/security-documents-generator#14]
# Background

A bug was created [here](https://github.com/elastic/kibana/issues/187072), showing that the `_id` of alert documents generated by the [security-documents-generator](https://github.com/elastic/security-documents-generator) do not match the `kibana.alert.uuid` field. The Alerts framework sets these two values to the same thing, and when they do not match, certain workflows do not function as expected (as mentioned in the bug above).

# Acceptance Criteria
- [x] The generated alert `_id` and `kibana.alert.uuid` fields should equal one another
- [x] Verify that the bug above is no longer reproducible afterwards by enabling the risk engine and looking at the "Rule Name" of Alert risk contributions

**Comment by machadoum** [comment]
PR https://github.com/elastic/security-documents-generator/pull/15

**Comment by jaredburgettelastic** [comment]
Closing, as the PR has been merged
